on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ShimejiEE
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
    - name: Setup Java
      uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: zulu
    - name: Build with Maven
      run: cd ShimejiEE-cross-platform |
        mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: ShimejiEE-${{ matrix.os }}
        path: ShimejiEE-cross-platform/target/ShimejiEE
  
